name: Jave8 CI with Actions

on:
  push:
    branches:
      - develop

env:
  IMAGE_NAME: qianguangfu
  APP_JAR_DIR: target/actions-0.0.1-SNAPSHOT.jar

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: |-
          mvn package -U -Dcodegen.skip -Dmaven.test.skip=true
          mv $APP_JAR_DIR app.jar
          docker build -f Dockerfile -t $IMAGE_NAME .      
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest,${{ env.STATE_RELEASE_VERSION }}"
