name: Jave8 CICD with Actions

on:
  push:
    branches:
      - sit-deploy
    tags:
      - 'v*'

env:
  IMAGE_NAME: actions
  PROJECT_DIR: actions-server
  APP_JAR_DIR: target/actions-0.0.1-SNAPSHOT.jar

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "测试成功"

  compile-build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: |-
          mvn package -U -Dcodegen.skip -Dmaven.test.skip=true
          mv $APP_JAR_DIR app.jar
          docker build -f Dockerfile -t $IMAGE_NAME .
      - uses: elgohr/Publish-Docker-Github-Action@master
        env:
          IMOGE_NAME: $IMAGE_NAME
        with:
          registry: registry.cn-shanghai.aliyuncs.com
          name: ${{ secrets.ALIYUN_IMAGE_REGISTRY }}/IMOGE_NAME
          username: ${{ secrets.ALIYUN_IMAGE_USERNAME }}
          password: ${{ secrets.ALIYUN_IMAGE_PASSWORD }}
          tags: "latest",${{ env.STATE_RELEASE_VERSION }}

  deploy:
    needs: compile-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: garygrossgarten/github-action-scp@release
        with:
          local: deploy.sh
          remote: deploy.sh
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASS }}
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASS }}
          port: 22
          script: |-
            chmod +x deploy.sh
            sh deploy.sh
            rm -rf deploy.sh
